In [1]:
import pandas as pd

In [6]:
weather_df = pd.read_csv("../data/weather_data_[2019].csv", delimiter = "\t")
weather_df.head(5)

,time,month,temperature,feelslike,wind,direction,gust,cloud,humidity,precipitation,pressure,weather
0,00:00,1,27.0,28.0,17.0,N,27.0,46.0,58.0,0.0,1012.0,Partly cloudy
1,03:00,1,27.0,28.0,17.0,N,27.0,35.0,59.0,0.0,1011.0,Partly cloudy
2,06:00,1,26.0,28.0,13.0,NNE,21.0,58.0,64.0,0.1,1012.0,Partly cloudy
3,09:00,1,27.0,28.0,17.0,NNE,23.0,40.0,62.0,0.1,1014.0,Patchy light drizzle
4,12:00,1,28.0,30.0,16.0,NNE,22.0,66.0,60.0,0.1,1013.0,Partly cloudy